//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipMain.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Urun_Cıkıs
    {
        public string Sicil_No { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Barkod { get; set; }
        public string Urun_adi { get; set; }
        public Nullable<int> Adet { get; set; }
        public string Tip { get; set; }
        public Nullable<System.DateTime> Cıkıs_Tarihi { get; set; }
        public int Hareket_ID { get; set; }
    }
}
