//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipMain.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urun_Hareket
    {
        public int Hareket_ID { get; set; }
        public int Urun_ID { get; set; }
        public Nullable<int> Personel_ID { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<System.DateTime> Cıkıs_Tarihi { get; set; }
    
        public virtual Personel Personel { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
