//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipMain.Veritabani
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public Urunler()
        {
            this.Urun_Hareket = new HashSet<Urun_Hareket>();
        }
        public override string ToString()
        {
            return Ad;
        }
        public int UrunID { get; set; }
        public string Barkod { get; set; }
        public string Ad { get; set; }
        public Nullable<short> Adet { get; set; }
        public Nullable<int> Tipi_ID { get; set; }
        public Nullable<int> Kategori_ID { get; set; }
        public Nullable<System.DateTime> Giris_Tarihi { get; set; }
    
        public virtual Kategori Kategori { get; set; }
        public virtual Tip Tip { get; set; }
        public virtual ICollection<Urun_Hareket> Urun_Hareket { get; set; }
    }
}
